server:
    port: 4004

spring:
    cloud:
        gateway:
            routes:
                - id: patient-service-routes
                  uri: http://patient-service:4000
                  predicates:
                    - Path=/api/paitents/**
                  filters:
                   - StripPrefix=1
                - id: api-docs-patient-routes
                  uri: http://patient-service:4000
                  predicates:
                    - Path=/api-docs/paitents
                  filters:
                    - RewritePath=/api-docs/patients,/v3/api-docs
                    

